apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f kubernetes.production.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: visualizer
  name: visualizer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: visualizer
    spec:
      containers:
      - image: dockersamples/visualizer:stable
        name: visualizer
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: visualizer-claim0
      restartPolicy: Always
      volumes:
      - name: visualizer-claim0
        persistentVolumeClaim:
          claimName: visualizer-claim0
status: {}
