version: '3'

services:
  devopsproject:
    image: dannybrouwers/devopsproject
    container_name: devopsprojectcontainer
    ports:
    - "1232:80"
    environment:
    - WEBAPI_ENVIRONMENT=webapicontainer
    links:
    - webapi
    build:
      context: .
      dockerfile: DevOpsProject/Dockerfile

  webapi:
    image: dannybrouwers/webapi
    container_name: webapicontainer
    build:
      context: .
      dockerfile: WebApi/Dockerfile