version: '3'

services:
  devopsproject:
    image: devopsproject
    container_name: devopsprojectcontainer2
    ports:
    - "1231:80"
    environment:
    - WEBAPI_ENVIRONMENT=webapicontainer2
    links:
    - webapi
    build:
      context: .
      dockerfile: DevOpsProject/Dockerfile

  webapi:
    image: webapi
    container_name: webapicontainer2
    build:
      context: .
      dockerfile: WebApi/Dockerfile