version: '3.1'

services:
  devopsproject:
    image: dannybrouwers/devopsproject:latest
    networks:
    - personnetwork
    secrets:
    - my_external_secret
    ports:
    - "1230:80"
    environment:
    - WEBAPI_ENVIRONMENT=webapicontainer
    
  webapi:
    image: dannybrouwers/webapi:latest
    deploy:
        replicas: 2        
    networks:
      personnetwork:
        aliases: 
          - webapicontainer
      
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - personnetwork     
      
  nginxtest:
    image: library/nginx
    ports:
    - "80:80"
    volumes:
    - "configuration:/etc/nginx/conf.d"
    networks:
    - personnetwork
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  my_external_secret:
    external: true

networks:
  personnetwork:
  
volumes:
  configuration:
        external: true