version: '3'

services:
  devopsproject:
    image: devopsproject
    container_name: devopsprojectcontainer
    environment:
    - WEBAPI_ENVIRONMENT=webapicontainer
    links:
    - webapi
    build:
      context: .
      dockerfile: DevOpsProject/Dockerfile

  webapi:
    image: webapi
    container_name: webapicontainer
    build:
      context: .
      dockerfile: WebApi/Dockerfile