version: '3'

services:
  devopsproject:
    image: devopsproject
    build:
      context: .
      dockerfile: DevOpsProject/Dockerfile

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

