version: '3.6'

services:
  devopsproject:
    image: database/devopsproject
    container_name: devopsprojectcontainer
    build:
      context: .
      dockerfile: DevOpsProject/Dockerfile

  webapi:
    image: database/webapi
    container_name: webapicontainer
    build:
      context: .
      dockerfile: WebApi/Dockerfile