version: '3.4'

services:
  devopsproject:
    image: roserdev01.azurecr.io/devopsproject
    container_name: devopsprojectcontainer
    ports:
    - "1232:80"
    environment:
    - WEBAPI_ENVIRONMENT=webapicontainer
    links:
    - webapi
    build:
      context: .
      dockerfile: DevOpsProject/Dockerfile

  webapi:
    image: roserdev01.azurecr.io/webapi
    container_name: webapicontainer
    build:
      context: .
      dockerfile: WebApi/Dockerfile