version: '3'

services:
  devopsproject:
    image: devopsproject
    container_name: devopsprojectcontainer
    ports:
    - 1239:80
    depends_on:
      - webapi
    build:
      context: .
      dockerfile: DevOpsProject/Dockerfile

  webapi:
    image: webapi
    container_name: webapicontainer
    build:
      context: .
      dockerfile: WebApi/Dockerfile