using System;
using System.Collections.Generic;

namespace WebApi.Database
{
    public partial class TblBolting
    {
        public TblBolting()
        {
            TblBlindPoint = new HashSet<TblBlindPoint>();
            TblTemplateBlindPoint = new HashSet<TblTemplateBlindPoint>();
        }

        public long PkBoltingid { get; set; }
        public long FkFlangetypeid { get; set; }
        public long? FkFlangesubtypeid { get; set; }
        public long FkBolttypeid { get; set; }
        public long? FkTorqtypeid { get; set; }
        public long? FkSwUnitofmeasurementid { get; set; }
        public long? FkBoltareaUnitofmeasurementid { get; set; }
        public long? FkBoltlimitsUnitofmeasurementid { get; set; }
        public long? FkBoltlgripUnitofmeasurementid { get; set; }
        public long? FkBolttorqvalueUnitofmeasurementid { get; set; }
        public int Boltqty { get; set; }
        public string Sw { get; set; }
        public string Boltarea { get; set; }
        public string Boltlimits { get; set; }
        public string Boltlgrip { get; set; }
        public string Bolttorqvalue { get; set; }
        public string Remark { get; set; }
        public string Createcomputer { get; set; }
        public string Createuser { get; set; }
        public DateTime Createdate { get; set; }
        public string Modifycomputer { get; set; }
        public string Modifyuser { get; set; }
        public DateTime Modifydate { get; set; }
        public long? FkDiaid { get; set; }
        public long? FkLbsid { get; set; }
        public long? FkDnid { get; set; }
        public long? FkPnid { get; set; }
        public long? FkBoltdiameterdiaid { get; set; }
        public long? FkBoltdiameterdnid { get; set; }
        public int? Compression { get; set; }
        public int? Additionalboltsqty { get; set; }
        public int? Washersqty { get; set; }
        public int? Washersthk { get; set; }
        public int? Requiredboltloadvalue { get; set; }
        public int? Bolttorqmaxvalue { get; set; }
        public int? Yieldpercentage { get; set; }
        public int? Boltstress { get; set; }
        public int? Jackpressuretouse { get; set; }
        public int? Numberoftensionersrequired { get; set; }
        public int? Gasketarticlenumer { get; set; }
        public int? Gasketthk { get; set; }
        public int? Boltarticleno { get; set; }
        public int? Tensioningvaluea { get; set; }
        public int? Tensioningvalueb { get; set; }
        public int? Breakloosepressure { get; set; }
        public int? Bolttensiontighten { get; set; }
        public int? Bolttensioncheck { get; set; }
        public int? Maxtensioningpress { get; set; }
        public int? Residualboltstress { get; set; }
        public int? Residualbolttension { get; set; }
        public int? Relaxationfactor { get; set; }
        public int? Finalreqstress { get; set; }
        public int? Finalreqboltstress { get; set; }
        public int? Reqboltload { get; set; }
        public int? Griplength { get; set; }
        public int? Yieldpoint { get; set; }
        public int? Toolarea { get; set; }
        public int? Pumpsetting { get; set; }
        public int? Pass1 { get; set; }
        public int? Pass2 { get; set; }
        public int? Pass3 { get; set; }
        public int? Pass4 { get; set; }
        public int? Pass5 { get; set; }
        public int? Pass1percentage { get; set; }
        public int? Pass2percentage { get; set; }
        public int? Pass3percentage { get; set; }
        public int? Pass4percentage { get; set; }
        public int? Pass5percentage { get; set; }
        public string Wrenchsizetype { get; set; }
        public string Threadpitch { get; set; }
        public string Protectioncap { get; set; }
        public string Specialboltinfo { get; set; }
        public decimal? Boltelongation { get; set; }
        public string Boltelongationmethod { get; set; }
        public string Liningtype { get; set; }
        public decimal? Gasketod { get; set; }
        public string Linedflange { get; set; }
        public decimal? Gasketid { get; set; }
        public long? FkBoltelongationUnitofmeasurementid { get; set; }
        public long? FkJackpressureUnitofmeasurementid { get; set; }
        public long? FkTensioningvalueAUnitofmeasurementid { get; set; }
        public long? FkTensioningvalueBUnitofmeasurementid { get; set; }
        public long? FkBreaklooseUnitofmeasurementid { get; set; }
        public long? FkBolttensiontightenUnitofmeasurementid { get; set; }
        public long? FkBolttensioncheckUnitofmeasurementid { get; set; }
        public long? FkMaxtensioningpressUnitofmeasurementid { get; set; }
        public long? FkResidualboltstressUnitofmeasurementid { get; set; }
        public long? FkResidualbolttensionUnitofmeasurementid { get; set; }
        public long? FkRelaxationfactorUnitofmeasurementid { get; set; }
        public long? FkFinalreqstressUnitofmeasurementid { get; set; }
        public long? FkFinalreqboltstressUnitofmeasurementid { get; set; }
        public long? FkReqboltloadUnitofmeasurementid { get; set; }
        public long? FkGriplengthUnitofmeasurementid { get; set; }
        public long? FkYieldpointUnitofmeasurementid { get; set; }
        public long? FkToolareaUnitofmeasurementid { get; set; }
        public long? FkPumpsettingUnitofmeasurementid { get; set; }
        public long? FkPass1Unitofmeasurementid { get; set; }
        public long? FkPass2Unitofmeasurementid { get; set; }
        public long? FkPass3Unitofmeasurementid { get; set; }
        public long? FkPass4Unitofmeasurementid { get; set; }
        public long? FkPass5Unitofmeasurementid { get; set; }
        public long? FkFlangeBasematerialid { get; set; }
        public long? FkGasketBasematerialid { get; set; }
        public long? FkBoltBasematerialid { get; set; }
        public long? FkBoltCertificateid { get; set; }
        public long? FkNutBasematerialid { get; set; }
        public long? FkWashersBasematerialid { get; set; }
        public long? FkWeldnormid { get; set; }
        public long? FkCriticalityid { get; set; }
        public long? FkRingjointid { get; set; }
        public long? FkMaxoffsetflangefacesid { get; set; }
        public long? FkLubricantid { get; set; }
        public long? FkFrictionid { get; set; }
        public long? FkThreadformid { get; set; }
        public long? FkConnectionid { get; set; }
        public long? FkGaskettypeid { get; set; }
        public long? FkAdditionalboltdiameterdiaid { get; set; }
        public long? FkAdditionalboltdiameterdnid { get; set; }
        public long? FkCompressionidUnitofmeasurementid { get; set; }
        public long? FkAdditionalbolttypeid { get; set; }
        public long? FkWashersthkUnitofmeasurementid { get; set; }
        public long? FkBoltstressUnitofmeasurementid { get; set; }
        public long? FkBolttorqmaxvalueUnitofmeasurementid { get; set; }
        public string Specialnote { get; set; }
        public decimal? Boltlengthinch { get; set; }
        public decimal? Boltlengthmm { get; set; }
        public decimal? Additionalboltlengthinch { get; set; }
        public decimal? Additionalboltlengthmm { get; set; }
        public int? Tightentorquedungreased { get; set; }
        public int? Tightentorquedgreased { get; set; }

        public TblDia FkAdditionalboltdiameterdia { get; set; }
        public TblDn FkAdditionalboltdiameterdn { get; set; }
        public TblBoltType FkAdditionalbolttype { get; set; }
        public TblBaseMaterial FkBoltBasematerial { get; set; }
        public TblBaseMaterial FkBoltCertificate { get; set; }
        public TblUnitOfMeasurement FkBoltareaUnitofmeasurement { get; set; }
        public TblDia FkBoltdiameterdia { get; set; }
        public TblDn FkBoltdiameterdn { get; set; }
        public TblUnitOfMeasurement FkBoltelongationUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkBoltlgripUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkBoltlimitsUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkBoltstressUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkBolttensioncheckUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkBolttensiontightenUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkBolttorqmaxvalueUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkBolttorqvalueUnitofmeasurement { get; set; }
        public TblBoltType FkBolttype { get; set; }
        public TblUnitOfMeasurement FkBreaklooseUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkCompressionidUnitofmeasurement { get; set; }
        public TblConnection FkConnection { get; set; }
        public TblCriticality FkCriticality { get; set; }
        public TblDia FkDia { get; set; }
        public TblDn FkDn { get; set; }
        public TblUnitOfMeasurement FkFinalreqboltstressUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkFinalreqstressUnitofmeasurement { get; set; }
        public TblBaseMaterial FkFlangeBasematerial { get; set; }
        public TblFlangeSubType FkFlangesubtype { get; set; }
        public TblFlangeType FkFlangetype { get; set; }
        public TblFriction FkFriction { get; set; }
        public TblBaseMaterial FkGasketBasematerial { get; set; }
        public TblGasketType FkGaskettype { get; set; }
        public TblUnitOfMeasurement FkGriplengthUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkJackpressureUnitofmeasurement { get; set; }
        public TblLbs FkLbs { get; set; }
        public TblLubricant FkLubricant { get; set; }
        public TblMaxOffsetFlangeFaces FkMaxoffsetflangefaces { get; set; }
        public TblUnitOfMeasurement FkMaxtensioningpressUnitofmeasurement { get; set; }
        public TblBaseMaterial FkNutBasematerial { get; set; }
        public TblUnitOfMeasurement FkPass1Unitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkPass2Unitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkPass3Unitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkPass4Unitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkPass5Unitofmeasurement { get; set; }
        public TblPn FkPn { get; set; }
        public TblUnitOfMeasurement FkPumpsettingUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkRelaxationfactorUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkReqboltloadUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkResidualboltstressUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkResidualbolttensionUnitofmeasurement { get; set; }
        public TblRingJoint FkRingjoint { get; set; }
        public TblUnitOfMeasurement FkSwUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkTensioningvalueAUnitofmeasurement { get; set; }
        public TblUnitOfMeasurement FkTensioningvalueBUnitofmeasurement { get; set; }
        public TblThreadForm FkThreadform { get; set; }
        public TblUnitOfMeasurement FkToolareaUnitofmeasurement { get; set; }
        public TblTorqType FkTorqtype { get; set; }
        public TblBaseMaterial FkWashersBasematerial { get; set; }
        public TblUnitOfMeasurement FkWashersthkUnitofmeasurement { get; set; }
        public TblWeldNorm FkWeldnorm { get; set; }
        public TblUnitOfMeasurement FkYieldpointUnitofmeasurement { get; set; }
        public ICollection<TblBlindPoint> TblBlindPoint { get; set; }
        public ICollection<TblTemplateBlindPoint> TblTemplateBlindPoint { get; set; }
    }
}
