using System;
using System.Collections.Generic;

namespace WebApi.Database
{
    public partial class TblSetting
    {
        public int PkSettingid { get; set; }
        public int Dbversion { get; set; }
        public string Createcomputer { get; set; }
        public string Createuser { get; set; }
        public DateTime Createdate { get; set; }
        public string Modifycomputer { get; set; }
        public string Modifyuser { get; set; }
        public DateTime Modifydate { get; set; }
        public bool Riskusevalues { get; set; }
        public string Supporteduploadfiles { get; set; }
        public string Supportedopenfiles { get; set; }
        public bool Hidedeleted { get; set; }
        public string Overallriskcaption { get; set; }
        public decimal? Estimatedfactor { get; set; }
        public bool? Calcmaintenance { get; set; }
        public bool? Calcproduction { get; set; }
        public string Sigbox1 { get; set; }
        public string Sigbox2 { get; set; }
        public string Sigbox3 { get; set; }
        public string Sigbox4 { get; set; }
        public string Sigbox5 { get; set; }
        public string Sigbox6 { get; set; }
        public string Rpt04 { get; set; }
        public string Currency { get; set; }
        public string Attachmentcopypath { get; set; }
        public int Attachmentsavemethod { get; set; }
        public bool Autologon { get; set; }
        public string RptLi02 { get; set; }
        public string RptWp00 { get; set; }
        public string RptWp01 { get; set; }
        public string RptLi04 { get; set; }
        public string Wisigbox1 { get; set; }
        public string Wisigbox2 { get; set; }
        public string Wisigbox3 { get; set; }
        public string Wisigbox4 { get; set; }
        public string Wisigbox5 { get; set; }
        public string Wisigbox6 { get; set; }
        public int Importkeyfield { get; set; }
        public long? FkDefaultlogoid { get; set; }
        public string Wikiusername { get; set; }
        public string Wikipassword { get; set; }
        public int Repairrelations { get; set; }
        public int Prefilldatadate { get; set; }
        public string Defaultcalendarworkhours { get; set; }
        public int Maxcyclelength { get; set; }
        public bool Certificatennrisprefixwithautonumber { get; set; }
        public int? Touchidletime { get; set; }
        public int? Touchquestionidletime { get; set; }
        public decimal? Touchfont { get; set; }
        public bool Touchisuserscopefiltering { get; set; }
        public bool Touchnbhenabled { get; set; }
        public bool Touchistimetracking { get; set; }
        public decimal? Touchmaxhoursday { get; set; }
        public int? Touchcanbookdaysback { get; set; }
        public int? Touchnbhcanbookdaysforward { get; set; }
        public string P6javaexepath { get; set; }
        public string P6apipath { get; set; }
        public string P6instancename { get; set; }
        public DateTime Actualstarttime { get; set; }
        public DateTime Actualfinishtime { get; set; }
        public int Firstdayofweek { get; set; }
        public int P6javainitialheapsize { get; set; }
        public int P6javamaximumheapsize { get; set; }
        public int Touchscopefield { get; set; }
        public string Ptwnrformat { get; set; }
        public bool? Distanceinkm { get; set; }
        public int? Hourbookamount { get; set; }
        public long? FkMasterdatainterfacelogoid { get; set; }
        public string Mdbtninterfacecaption { get; set; }
        public string P6apiversion { get; set; }
        public int P6apibatchsize { get; set; }
        public string P6pmdbusername { get; set; }
        public string P6pmdbpassword { get; set; }
        public int P6heartbeattimeout { get; set; }
        public int Httprequesttimeout { get; set; }
        public string Preqcmemo { get; set; }
        public string Visualqcmemo { get; set; }
        public string Postqcmemo { get; set; }
        public string Mdbdataprovider { get; set; }
        public string Accdbdataprovider { get; set; }
        public bool P6exportallsbsmilestones { get; set; }
        public int? Reviewcountfull { get; set; }
        public bool Invertriskaxis { get; set; }
        public long? Startnumberchangerequest { get; set; }
        public bool Touchpinisrequired { get; set; }
        public int Permitplanningdate { get; set; }
        public bool Passwordrequirecapitalchar { get; set; }
        public bool Passwordrequirenonalphachar { get; set; }
        public bool Passwordrequirenumericchar { get; set; }
        public int Passwordcharminimumcount { get; set; }
        public int Activitycodelength { get; set; }
        public int? Riskchecklistcountfull { get; set; }
        public bool Touchisbrutonetto { get; set; }
        public int Touchclockovertimeafterminutes { get; set; }
        public int Touchstarttimeexceptionminutes { get; set; }
        public int Touchendtimeexceptionminutes { get; set; }
        public int Touchroundstarttime { get; set; }
        public int Touchroundendtime { get; set; }
        public string Finalqcmemo { get; set; }
        public string Documentnrformat { get; set; }
        public string Tempfolder { get; set; }
        public bool Autocleanuptempfolder { get; set; }
        public bool Usedefaultdocumentlabelattachments { get; set; }
        public bool Denyaddingdeletedscopes { get; set; }
        public bool P6exportroles { get; set; }
        public int P6maxactivityidlength { get; set; }
        public int Touchlookahead { get; set; }
        public int Normaltimeout { get; set; }
        public int Hightimeout { get; set; }
        public int Maxtimeout { get; set; }
        public int Daextimeout { get; set; }
        public bool Usescoperequestnoforrosersystems { get; set; }
        public int Touchscreenrefreshtime { get; set; }
        public byte? Historicalpasswordstokeep { get; set; }
        public int? Maxloginattempt { get; set; }
        public int? Dayspasswordisvalid { get; set; }
        public string Wikiurl { get; set; }
        public int Technicaldatareportdepth { get; set; }
        public int Technicaldatareportbasedon { get; set; }
        public string Technicaldatareportseparator { get; set; }
        public bool Useencryption { get; set; }
        public bool Usecloseconfirmation { get; set; }
        public int Maxsuggestions { get; set; }
        public int Minsuggestionpercentage { get; set; }
        public int Activityprogressordertype { get; set; }
        public bool Mandatoryscanafterprogress { get; set; }
        public int Isolationactivitysequence { get; set; }
        public string Progressloginurl { get; set; }
        public int Reportpaperkind { get; set; }
        public int Reportpaperkindlargereport { get; set; }
        public bool Autosendemailonactioncreation { get; set; }
        public bool Autosendmailtoprojectleaderonreviewscompleted { get; set; }
        public bool Usestartwork { get; set; }

        public TblLogo FkDefaultlogo { get; set; }
        public TblLogo FkMasterdatainterfacelogo { get; set; }
    }
}
