version: '3.6'

services:
  devopsproject:
    image: dannybrouwers/devopsproject
    networks:
    - personnetwork
    secrets:
    - my_external_secret
    ports:
    - "1231:80"
    environment:
    - WEBAPI_ENVIRONMENT=webapicontainer
    deploy:
      placement:
        constraints: [node.role == worker]
    
  webapi:
    image: dannybrouwers/webapi
    deploy:
        replicas: 1   
      placement:
        constraints: [node.role == worker]
    networks:
      personnetwork:
        aliases: 
          - webapicontainer 

secrets:
  my_external_secret:
    external: true

networks:
  personnetwork:
  
volumes:
  configuration:
        external: true