version: '3.6'

services:
  devopsproject:
    image: database/devopsproject
    networks:
    - personnetwork
    secrets:
    - my_external_secret
    ports:
    - "1230:80"
    environment:
    - WEBAPI_ENVIRONMENT=webapicontainer
    
  webapi:
    image: database/webapi
    ports:
    - "1231:80"
    volumes:
      - C:\Users\Devopsproject\Production\appsettings.json:/app/appsettings.json
    deploy:
        replicas: 1   
    networks:
      personnetwork:
        aliases: 
          - webapicontainer
      
secrets:
  my_external_secret:
    external: true

networks:
  personnetwork:
  
volumes:
  configuration:
        external: true